name: refresh-events
on:
  workflow_dispatch:
  push:
    branches:
      - node-bot
  schedule:
    - cron: '0 * * * *'
jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run bun:start
        env:
          NOTION_KEY: ${{secrets.NOTION_KEY}}
          DATABASE_ID: ${{secrets.DATABASE_ID}}
          OAUTH_CLIENTID: ${{secrets.OAUTH_CLIENTID}}
          OAUTH_SECRET: ${{secrets.OAUTH_SECRET}}
          REFRESH_TOKEN: ${{secrets.REFRESH_TOKEN}}
